# Redirect non-www to www
server {
    listen 80;
    listen [::]:80;

    server_name brihaspathi.com;

    return 301 https://www.brihaspathi.com$request_uri;
}

# Main www domain
server {
    listen 80;
    listen [::]:80;

    server_name www.brihaspathi.com;

    # 🔥 BACKEND - PORT 2334 (CMS and Strapi API)
    location ^~ /cms-api/ {
        proxy_pass http://183.82.117.36:2334/;
        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # 🔥 BACKEND - PORT 2334 (HR login and /strapi/* paths)
    location ^~ /strapi/ {
        proxy_pass http://183.82.117.36:2334/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $server_name;
        proxy_set_header X-Forwarded-Port $server_port;
        proxy_redirect off;
        proxy_buffering off;
    }

    # 🔥 BACKEND - PORT 1337
    location ^~ /backend-api/ {
        proxy_pass http://183.82.117.36:1337/;
        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # 🔹 NEXT JS FRONTEND
    location / {
       proxy_pass http://127.0.0.1:3001;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_cache_bypass $http_upgrade;
    }
}